show databases;
create table Semp 
(
 EMPNO CHAR(4),
 EMPNAME CHAR(20),
 BASIC FLOAT(9,2),
 DEPTNO CHAR(2),
 DEPTHEAD CHAR(4)
);
SELECT * FROM Semp;
create table SEMP
(
EMPNO CHAR(4),
 EMPNAME CHAR(20),
 BASIC FLOAT(9,2),
 DEPTNO CHAR(2),
 DEPTHEAD CHAR(4)
);
CREATE TABLE SDEPT
(
DEPTNO CHAR(2),
DEPTNAME CHAR (15)
);
SELECT * FROM SDEPT;
insert into SDEPT VALUES
('20','Training');
select * from SDEPT;

INSERT INTO SEMP (EMPNO,EMPNAME,BASIC,DEPTNO)VALUES
('0001', 'SUNIL', 6000, 10);

INSERT INTO SEMP (EMPNO,EMPNAME,BASIC,DEPTNO)VALUES
('0002', 'HIREN', 8000, 20);

INSERT INTO SEMP (EMPNO,EMPNAME,BASIC,DEPTNO,DEPTHEAD)VALUES
(0003, 'ALI', 4000, 10, 0001);
INSERT INTO SEMP (EMPNO,EMPNAME,BASIC,DEPTHEAD)VALUES
('0004', 'GEORGE', 6000, '0002');
SELECT * FROM SEMP;

UPDATE SEMP
SET EMPNO = '0003'
WHERE EMPNAME = 'ALI';
SELECT * FROM SEMP;

ALTER TABLE SEMP
RENAME COLUMN EMPNO TO EMPN;
SELECT * FROM SEMP;

ALTER TABLE SEMP
RENAME COLUMN EMPN TO EMPNO;

SELECT * FROM SEMP;

UPDATE SEMP
SET DEPTHEAD='0001'
WHERE EMPNO='0003';

SELECT * FROM SEMP;

CREATE TABLE SUPPLIER(
`S#` CHAR(4),
Sname char(15),
Status char(20),
City char(20)
);
select * from SUPPLIER;
CREATE TABLE PARTS(
`P#` CHAR(4),
Pname char(15),
Color char(20),
Weigh char(4),
City char(20)
);

CREATE TABLE PROJECTS(
`J#` CHAR(4),
Jname char(15),
City char(20)
);

CREATE TABLE SUPPLIER_PARTS_PROJECTS(
`S#` CHAR(4),
`P#` CHAR(4),
`J#` CHAR(4),
Qty  CHAR(15)

);
SELECT * FROM SUPPLIER_PARTS_PROJECTS;
SHOW tableS;
ALTER TABLE SUPPLIER RENAME TO S;
ALTER TABLE PARTS RENAME TO P;
ALTER TABLE PROJECTS RENAME TO J;
ALTER TABLE SUPPLIER_PARTS_PROJECTS RENAME TO SPJ;

SHOW TABLE STATUS;
INSERT INTO S VALUES(
('S1','ANEESH','LAKDIYA','PUNE'),
('S2','AMOL','KHARRA','NASHIK'),
('S3','AKASH KHANKE','INFINITY','CHANDRAPUR')
);

ALTER TABLE S RENAME COLUMN STATE TO Status;
INSERT INTO S VALUES
('S1','ANEESH',10,'PUNE'),
('S2','AMOL',20,'NASHIK'),
('S3','AKASH KHANKE',30,'CHANDRAPUR');


SELECT * FROM S where Sname != 'Amol';

insert into P values
('P1','cick','Black',50,'Phaltan'),
('P2','HORN','WHITE',20,'NAGPUR'),
('P3','CRANK_SHAFT','SILVER',12,'PATNA');

SELECT * FROM P;

INSERT INTO J VALUES('J1','BIKE','Paris'),
('J2','Car','london'),
('J3','Truck','Athens');

select * from spj;
insert into SPJ VALUES('S1','P1','J1',20),
('S2','P2','J2',30),
('S3','P3','J3',10);

select `S#`,Sname from S;
select Pname,Color from P where City= 'Patna';
select `S#` from S where City='Pune';
select * from S where City='Pune' OR City='Nashik';

select weigh, weigh*1000 'MILIGRAM',weigh/1000 'KILOGRAM' from P;

SELECT WEIGH FROM P WHERE WEIGH >12 AND WEIGH <50;
SELECT `S#` FROM S WHERE Status>=20;
SELECT City from S;

SELECT * FROM S
ORDER BY City DESC;

SELECT `S#` FROM S WHERE Status between 10 AND 20; 

ALTER TABLE P
RENAME COLUMN WEIGH TO WEIGHT;
SELECT * FROM P
;

SELECT Pname,Weight FROM P WHERE WEIGHT!=10 AND WEIGHT!=15;
SELECT Pname FROM P WHERE Pname LIKE 'C%T';
SELECT `S#` FROM S WHERE CITY LIKE 'P%';
SELECT Jname FROM J WHERE Jname LIKE 'C__';

SELECT UPPER(LEFT(word,1))+LOWER(SUBSTRING(word,2,LEN(word))) FROM Supplier;

